name: .NET

on:
  pull_request:
    branches: [ repo0.10 ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    strategy:
      matrix:
        versions: [ 0.10.0, 0.10.9, 0.10.10, 0.10.14, 0.10.16]

    steps:
    - uses: actions/checkout@v2
      with:
          submodules: 'true'
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Clean
      run: dotnet clean
      env:
        AVA_VER: ${{ matrix.versions }}
    - name: Restore
      run: dotnet restore
      env:
        AVA_VER: ${{ matrix.versions }}
    - name: Build
      run: dotnet build --no-restore
      env:
        AVA_VER: ${{ matrix.versions }}
    - name: Test
      run: dotnet test --no-build --verbosity normal
      env:
        AVA_VER: ${{ matrix.versions }}
